FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Src/UsersService/UsersService.csproj", "UsersService/"]
COPY ["config/nuget.dev.config", "UsersService/nuget.config"]
COPY ["Src/UsersService/DataModel/DataModel.csproj", "UsersService/DataModel/"]
COPY ["config/nuget.dev.config", "UsersService/DataModel/nuget.config"]
COPY ["Src/Shared/Core/Events/Shared.Core.Events.csproj", "Shared/Core/Events/"]
COPY ["config/nuget.dev.config", "Shared/Core/Events/nuget.config"]
COPY ["Src/Shared/Infrastructure/Shared.Infrastructure.csproj", "Shared/Infrastructure/"]
COPY ["config/nuget.dev.config", "Shared/Infrastructure/nuget.config"]
RUN dotnet restore "UsersService/UsersService.csproj" 
COPY Src/ .
WORKDIR "/src/UsersService"
RUN dotnet build "UsersService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "UsersService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UsersService.dll"]